version: '3.9'

name: "localstack-playground-environment"

services:
  localstack:
    image: ${LOCALSTACK_IMAGE}:${LOCALSTACK_TAG:-latest}
    env_file:
      - .env
    environment:
      - AWS_DEFAULT_REGION=${AWS_REGION:-eu-west-2}
      - DEBUG=${DEBUG-:DEBUG}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_SERVICES=dynamodb,sqs,s3,cloudformation
    volumes:
      - "./init-resources.sh:/etc/localstack/init/ready.d/init.sh:ro"
      - "./cfn-localstack-resources.yaml:/opt/code/cfn-templates/cfn-localstack-resources.yaml:ro"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack

  localstack-resources-setup:
    image: ${AWS_CLI_IMAGE}:${AWS_CLI_TAG:-latest}
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-aws-access-key-id}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-aws-secret-access-key}
      - AWS_DEFAULT_REGION=${AWS_REGION:-eu-west-2}
      - AWS_ENDPOINT_URL=${LOCALSTACK_URL}
    entrypoint: /bin/sh -c
    command: >
      "
        sleep 10
        aws dynamodb create-table --table-name Playground --attribute-definitions AttributeName=Play,AttributeType=S AttributeName=Ground,AttributeType=S --key-schema AttributeName=Play,KeyType=HASH AttributeName=Ground,KeyType=RANGE --provisioned-throughput ReadCapacityUnits=10,WriteCapacityUnits=5 --region ${AWS_REGION}
        aws dynamodb batch-write-item --request-items file://../dyanmodb/batch-data-01.json
        aws dynamodb describe-table --table-name Playground --output table
        aws s3 cp ../dyanmodb s3://bucket-uno --recursive
        aws s3 ls s3://bucket-uno
      "
    volumes:
      - ./dynamodb/data:/dyanmodb
    depends_on:
      - localstack
    networks:
      - localstack

networks:
  localstack:
