version: '3.9'

services:
  localstack:
    image: ${LOCALSTACK_IMAGE}:${LOCALSTACK_TAG:-latest}
    env_file:
      - .env
    environment:
      - AWS_DEFAULT_REGION=${AWS_REGION:-eu-west-2}
      - DEBUG=${DEBUG-:DEBUG}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_SERVICES=dynamodb,sqs,s3
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack

  localstack-resources-setup:
    image: ${AWS_CLI_IMAGE}:${AWS_CLI_TAG:-latest}
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-aws-access-key-id}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-aws-secret-access-key}
      - AWS_DEFAULT_REGION=${AWS_REGION:-eu-west-2}
    entrypoint: /bin/sh -c
    command: >
      "
        sleep 10
        aws dynamodb --endpoint-url=${LOCALSTACK_URL} create-table --table-name Playground --attribute-definitions AttributeName=Play,AttributeType=S AttributeName=Ground,AttributeType=S --key-schema AttributeName=Play,KeyType=HASH AttributeName=Ground,KeyType=RANGE --provisioned-throughput ReadCapacityUnits=10,WriteCapacityUnits=5 --region ${AWS_REGION}
        sleep 10
        aws dynamodb --endpoint-url=${LOCALSTACK_URL} batch-write-item --request-items file://../dyanmodb/batch-data-01.json
        aws dynamodb --endpoint-url=${LOCALSTACK_URL} describe-table --table-name Playground --output table
        sleep 10
        aws sqs create-queue --endpoint-url=${LOCALSTACK_URL} --queue-name ${AWS_QUEUE_NAME_1} --region ${AWS_REGION}
        sleep 10
        aws --endpoint-url=${LOCALSTACK_URL} s3 mb s3://${AWS_S3_BUCKET_NAME_1} --region ${AWS_REGION}
        sleep 10
        aws --endpoint-url=${LOCALSTACK_URL} s3 ls
      "
    volumes:
      - ./dynamodb/data:/dyanmodb
    depends_on:
      - localstack
    networks:
      - localstack

networks:
  localstack:
